# Node docker image with Cypress and Chrome pre-installed
image: cypress/browsers:node13.6.0-chrome80-ff72

cache:
  key: ${CI_COMMIT_REF_SLUG}

# Pipeline
stages:
  - install
  - build
  - test

# Jobs 
install_dependencies:
  stage: install
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - ls -la
    - yarn config set registry "https://registry.npm.taobao.org"
    - yarn

bundle_app:
  stage: build
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - ls -la
    - yarn build
  artifacts:
    paths:
      - build/

e2etest:    
  stage: test
  cache:
    policy: pull
    paths:
      - node_modules/
  script:
    - ls -la
     # start the server in the background
    - yarn start:ci

# NEW
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

cache:
  key:
    files:
       - package.json
  paths:
     - .npm
     - cache/Cypress
     - node_modules
# END NEW